INPUT:
  MIN_SIZE_TRAIN: (900, )
  MAX_SIZE_TRAIN: 1500
  MIN_SIZE_TEST: 900
  MAX_SIZE_TEST: 1500

MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  RPN:
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TEST: 300
    ANCHOR_SIZES: (32, 64, 128, 256)
  ROI_HEADS: 
    BATCH_SIZE_PER_IMAGE: 128
  REID_CONFIG:
    FEAT_DIM: 256
    NUM_IDS: 5532
  APNET: 
    BOX_PART_ON: False
    BOX_PADREG_ON: False
    TRAIN_PART: False
    TRAIN_PADREG: False

DATASETS:
  TRAIN: ("cuhk_train", )
  TEST: ("cuhk_test", "cuhk_query", )
  
SOLVER:
  BASE_LR: 0.0001
  WEIGHT_DECAY: 0.001
  STEPS: (30000, )
  MAX_ITER: 50000
  IMS_PER_BATCH: 4