INPUT:
  MIN_SIZE_TRAIN: (900, )
  MAX_SIZE_TRAIN: 1500
  MIN_SIZE_TEST: 900
  MAX_SIZE_TEST: 1500

MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  RPN:
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TEST: 300
    ANCHOR_SIZES: (32, 64, 128, 256)
  ROI_HEADS: 
    BATCH_SIZE_PER_IMAGE: 128
  REID_CONFIG:
    FEAT_DIM: 256
    NUM_IDS: 5532
  APNET: 
    BOX_PART_ON: True
    BOX_PADREG_ON: True
    TRAIN_PART: False
    TRAIN_PADREG: True
    DISCARD_NOKP: True
    PADREG_AUG_PER: 2
    PADREG_RAND_CUT: 0.5

DATASETS:
  TRAIN: ("cuhk_train", )
  TEST: ("cuhk_test", "cuhk_query", )

SOLVER:
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0001
  STEPS: (20000, )
  MAX_ITER: 120000
  IMS_PER_BATCH: 4

# 50, 000 OIM training done
# 90, 000 part training done

